home/urls.py
from django.urls import path

from recipes.views import home_recipe_view

urlpatterns = [
    path("", home_recipe_view, name="home"),
]

recipes/urls.py
from django.urls import path
from recipes import views

from .views import (
    AddRecipe,
    Recipes,
    RecipeDetail,
    DeleteRecipe,
    EditRecipe,
    bookmark_recipe,
    remove_bookmark,
    comment_edit,
    comment_delete,
    rate_recipe,
)

# 404
handler404 = views.custom_404

urlpatterns = [
    path("add_recipe/", AddRecipe.as_view(), name="add_recipe"),
    path("<slug:slug>/", RecipeDetail.as_view(), name="recipe_detail"),
    path("delete/<slug:slug>/", DeleteRecipe.as_view(), name="delete_recipe"),
    path("edit/<slug:slug>/", EditRecipe.as_view(), name="edit_recipe"),
    path("bookmark/<slug:slug>/", bookmark_recipe, name="bookmark_recipe"),
    path("remove-bookmark/<slug:slug>/", remove_bookmark, name="remove_bookmark"),
    path("rate_recipe/<int:recipe_id>/", rate_recipe, name="rate_recipe"),
    path(
        "<slug:slug>/edit_comment/<int:comment_id>", comment_edit, name="comment_edit"
    ),
    path(
        "<slug:slug>/delete_comment/<int:comment_id>",
        comment_delete,
        name="comment_delete",
    ),
    path("", Recipes.as_view(), name="recipes"),
]

zaitouna_website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("djrichtextfield/", include("djrichtextfield.urls")),
    path("recipes/", include("recipes.urls")),
    path("profiles/", include("profiles.urls")),
    path("", include("home.urls")),
]

recipes/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg
from djrichtextfield.models import RichTextField
from django_resized import ResizedImageField

# Choices here
DIFFICULTY = ((0, "Easy"), (1, "Medium"), (2, "Hard"))


# Create your models here.
class MealType(models.Model):
    """
    A model to represent meal types.
    """

    title = models.CharField(max_length=50)

    def __str__(self):
        return str(self.title)


class Recipe(models.Model):
    """
    Model to create recipe
    """

    user = models.ForeignKey(
        User, related_name="recipe_owner", on_delete=models.CASCADE
    )
    name = models.CharField(max_length=300, unique=True, null=False, blank=False)
    slug = models.SlugField(max_length=300, unique=True)
    description = models.CharField(max_length=500, null=False, blank=False)
    instructions = RichTextField(max_length=10000, null=False, blank=False)
    ingredients = RichTextField(max_length=10000, null=False, blank=False)
    image = ResizedImageField(
        size=[400, None],
        quality=85,
        upload_to="recipes/",
        # force_format="WEBP,PNG,JPNG",
        null=False,
        blank=False,
    )
    image_alt = models.CharField(max_length=100, null=False, blank=False)
    meal_type = models.ForeignKey(
        MealType, related_name="recipe_type", on_delete=models.CASCADE
    )
    is_weekly = models.BooleanField(default=False)
    difficulty = models.IntegerField(choices=DIFFICULTY, default=0)
    serves = models.PositiveIntegerField()
    prep_time = models.PositiveIntegerField(default=1)
    posted_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-posted_date"]

    def __str__(self):
        return str(self.name)


class Comment(models.Model):
    title = models.CharField(max_length=200, default="Wonderful Recipe")
    recipe = models.ForeignKey(
        Recipe, on_delete=models.CASCADE, related_name="comments"
    )
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="commenter")
    body = models.TextField()
    approved = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_on"]

    def __str__(self):
        return f"Comment {self.title} by {self.author}"


class Bookmark(models.Model):
    user = models.ForeignKey(User, related_name="bookmarks", on_delete=models.CASCADE)
    recipes = models.ManyToManyField("recipes.Recipe")


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="rater")
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE, related_name="ratings")
    rating = models.IntegerField(choices=[(i, str(i)) for i in range(1, 6)])

    def __str__(self):
        return f"{self.recipe} - {self.user}: {self.rating} stars"

    class Meta:
        unique_together = ("recipe", "user")  # Each user can rate a recipe only once

    @classmethod
    def get_average_rating(cls, recipe_id):
        average_rating = cls.objects.filter(recipe_id=recipe_id).aggregate(
            Avg("rating")
        )["rating__avg"]
        return average_rating or 0

recipes/forms.py
from django import forms
from djrichtextfield.widgets import RichTextWidget
from .models import Recipe, Comment


class RecipeForm(forms.ModelForm):
    """Form to create a recipe"""

    class Meta:
        model = Recipe
        fields = [
            "name",
            "description",
            "instructions",
            "ingredients",
            "image",
            "image_alt",
            "meal_type",
            "difficulty",
            "prep_time",
            "serves",
        ]
        ingredients = forms.CharField(widget=RichTextWidget())
        instructions = forms.CharField(widget=RichTextWidget())
        widget = {"description": forms.Textarea(attrs={"row": 5})}
        labels = {
            "name": "Recipe Name",
            "description": "Some More Description about the Recipe",
            "instructions": "The recipe instructions ",
            "ingredients": "The Recipe Ingredients",
            "image": "Image of your Recipe",
            "image_alt": "Description of your Image",
            "meal_type": "Pick which meal type your recipe is!",
            "difficulty": "Difficulty",
            "prep_time": "Cooking time in minutes",
            "serves": "Serves",
        }


class CommentForm(forms.ModelForm):
    """Form to comment on a recipe"""

    class Meta:
        model = Comment
        fields = [
            "title",
            "body",
        ]
        widget = {"body": forms.Textarea(attrs={"row": 5})}
        labels = {
            "title": "Comment Title",
            "body": "Tell us how you found the Recipe",
        }

recipes/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.views.generic import (
    CreateView,
    ListView,
    DetailView,
    DeleteView,
    UpdateView,
)
from django.utils.text import slugify
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, Avg, Count
from django.views.generic.edit import FormMixin
from django.contrib import messages
from django.http import HttpResponseRedirect
from .models import Recipe, MealType, Bookmark, Comment, Rating
from .forms import RecipeForm, CommentForm

# Show 10 recipes per page
MAX_RECORDS = 6


def home_recipe_view(request):
    """
    View for rendering the home page with a list of recipes and a weekly featured recipe.

    This view retrieves the weekly featured recipe and a list of all recipes with their
    average ratings. It paginates the recipe list and renders the home page template with
    the necessary data.

    Args:
        request (HttpRequest): The HTTP request object.

    Returns:
        HttpResponse: The HTTP response with the rendered home page template.
    """
    weekly_recipe = Recipe.objects.filter(is_weekly=True).last()
    recipe_list = Recipe.objects.annotate(average_rating=Avg("ratings__rating"))

    # Pagination
    paginator = Paginator(recipe_list, MAX_RECORDS)
    page_number = request.GET.get("page")
    try:
        recipe_list = paginator.page(page_number)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        recipe_list = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        recipe_list = paginator.page(paginator.num_pages)

    return render(
        request,
        "home/index.html",
        {
            "weekly_recipe": weekly_recipe,
            "recipe_list": recipe_list,
            "star_range": range(1, 6),
        },
    )


class Recipes(ListView):
    """
    List recipe View
    """

    template_name = "recipes/recipes.html"
    model = Recipe
    context_object_name = "recipes"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meal_types"] = MealType.objects.all()
        return context

    def get_queryset(self, **kwargs):
        query = self.request.GET.get("q", "")
        meal_type_id = self.request.GET.get("meal_type", "")
        # Start with all recipes
        recipes = self.model.objects.all()

        # Filter by search query if present
        if query:
            recipes = recipes.filter(
                Q(name__icontains=query)
                | Q(description__icontains=query)
                | Q(instructions__icontains=query)
            )

        # Filter by meal type if selected
        if meal_type_id:
            recipes = recipes.filter(meal_type_id=meal_type_id)

        return recipes


class AddRecipe(LoginRequiredMixin, CreateView):
    """
    Add recipe View
    """

    template_name = "recipes/add_recipe.html"
    model = Recipe
    form_class = RecipeForm
    success_url = "/recipes/"

    def form_valid(self, form):
        form.instance.user = self.request.user
        recipe_name = form.cleaned_data.get("name")
        form.instance.slug = slugify(recipe_name)
        form.instance.is_weekly = False
        return super(AddRecipe, self).form_valid(form)


class RecipeDetail(FormMixin, DetailView):
    """
    Display an individual :model:`Recipe`.

    **Context**

    ``Recipe``
        An instance of :model:`Recipe`.

    **Template:**

    :template:`blog/Recipe_detail.html`
    """

    template_name = "recipes/recipe_details.html"
    model = Recipe
    context_object_name = "recipe"
    form_class = CommentForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        recipe = self.object

        # Retrieve bookmarked for the recipe
        if self.request.user.is_authenticated:
            # Get the current user's bookmarks
            user_bookmarks = Bookmark.objects.filter(user=self.request.user)
            # Check if the current recipe is bookmarked by the user
            context["is_bookmarked"] = user_bookmarks.filter(
                recipes=self.object
            ).exists()
        else:
            context["is_bookmarked"] = False

        # Retrieve comments for the recipe
        comments = recipe.comments.order_by("-created_on")
        context["comments"] = comments
        context["comment_count"] = comments.filter(approved=True).count()
        context["comment_form"] = CommentForm



        # Retrieve average rating for the recipe
        rating_data = Rating.objects.filter(recipe=recipe).aggregate(
            Avg("rating"), Count("rating")
        )
        context["average_rating"] = rating_data["rating__avg"]
        context["rating_count"] = rating_data["rating__count"]
        context["star_range"] = range(1, 6)
        return context

    def post(self, request, *args, **kwargs):
        recipe = self.get_object()
        form = self.get_form()
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.recipe = recipe
            comment.save()
            # Add success message
            messages.success(self.request, "Comment submitted and awaiting approval")
            # return HttpResponseRedirect(request.path_info)  # Redirect to the same page
            return redirect("recipe_detail", slug=recipe.slug)
        else:
            return self.form_invalid(form)


class DeleteRecipe(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    """
    View for deleting a recipe.

    This view allows authenticated users to delete their own recipes. Only the user who owns
    the recipe can delete it.

    Attributes:
        model (Model): The model class representing the recipe.
        success_url (str): The URL to redirect to after successfully deleting the recipe.

    Methods:
        test_func(): Check if the user is allowed to delete the recipe.
    """

    model = Recipe
    success_url = "/recipes/"

    def test_func(self):
        return self.request.user == self.get_object().user


class EditRecipe(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    """
    View for editing a recipe.

    This view allows authenticated users to edit their own recipes. Only the user who owns
    the recipe can edit it.

    Attributes:
        template_name (str): The template to render for editing the recipe.
        model (Model): The model class representing the recipe.
        form_class (Form): The form class to use for editing the recipe.
        success_url (str): The URL to redirect to after successfully editing the recipe.

    Methods:
        test_func(): Check if the user is allowed to edit the recipe.
    """

    template_name = "recipes/edit_recipe.html"
    model = Recipe
    form_class = RecipeForm
    success_url = "/recipes/"

    def test_func(self):
        return self.request.user == self.get_object().user


@login_required()
def comment_edit(request, slug, comment_id):
    """
    view to edit comments
    """
    if request.method == "POST":
        recipe = get_object_or_404(Recipe, slug=slug)
        comment = get_object_or_404(Comment, pk=comment_id)
        # By specifying instance=comment, any changes made to the form will be applied to the existing Comment,
        # instead of creating a new one.
        comment_form = CommentForm(data=request.POST, instance=comment)

        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.recipe = recipe
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, "Comment Updated!")
        else:
            messages.add_message(request, messages.ERROR, "Error updating comment!")

    # reverse is a Django function that constructs a URL from the provided URL path name and any
    # relevant URL arguments: args=[slug].
    return HttpResponseRedirect(reverse("recipe_detail", args=[slug]))


@login_required()
def comment_delete(request, slug, comment_id):
    """
    view to delete comment
    """
    recipe = get_object_or_404(Recipe, slug=slug)
    comment = get_object_or_404(Comment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.ERROR, "Comment deleted!")
    else:
        messages.add_message(
            request, messages.ERROR, "You can only delete your own comments!"
        )

    return HttpResponseRedirect(reverse("recipe_detail", args=[slug]))


@login_required
def bookmark_recipe(request, slug):
    """
    View for bookmarking a recipe.

    This view allows authenticated users to bookmark a recipe. If the recipe is not already
    bookmarked by the user, it adds the recipe to the user's bookmarks.

    Args:
        request (HttpRequest): The HTTP request object.
        slug (str): The slug of the recipe to be bookmarked.

    Returns:
        HttpResponseRedirect: Redirects to the recipe detail page after bookmarking the recipe.
    """
    if request.method == "GET":
        user = request.user
        recipe = Recipe.objects.get(slug=slug)
        # Check if the recipe is already bookmarked
        if not Bookmark.objects.filter(user=user, recipes=recipe).exists():
            # If not bookmarked, add it to the user's bookmarks
            bookmark, created = Bookmark.objects.get_or_create(user=user)
            bookmark.recipes.add(recipe)
            messages.success(
                request, "Recipe was added to bookmarked list Successfully!"
            )
    # Redirect back to the recipe detail page

recipes/templates/recipes/add_recipe.html
{% extends 'base.html'%}
{% block title %} Add Recipe{% endblock %}
{% block content %}
<div class="container">
    <form action="" method="post" enctype="multipart/form-data" class="form p-2">

        <div class="form-title text-center p-4 justify-content-center">
            <h1>Add Recipe</h1>
        </div>
        {% csrf_token %}
        {{ form.media }}
        {{ form |crispy }}
        <div class="text-center mb-5">
            <button type="submit" class="btn btn-primary mt-2">Create Recipe</button>
        </div>
    </form>
</div>
{% endblock %}

recipes/templates/recipes/recipe_details.html
{% extends 'base.html' %}
{%block title %}Recipe Detail - {{recipe.name}}{% endblock%}
{% load static %}
{% load social_share %}
{% load crispy_forms_tags %}
{%block content %}
<div class="container">
  <!-- Title Section -->
  <div class="row mt-5">
    <div class="col-12 col-sm-9">
      <h1>{{recipe.name}}</h1>
    </div>


    <div class="col-12 col-sm-3 text-end tools">
    {% if request.user == recipe.user %}
      <a href="{% url 'edit_recipe' recipe.slug %}" class="edit-icon me-3"><i class="fa-regular fa-pen-to-square"></i></a>
      <a href="{% url 'delete_recipe' recipe.slug %}" class="delete-icon me-3"><i class="fa-regular fa-trash-can"></i></a>
    {% endif %}
      <a href="#" class="share-icon me-3" data-bs-toggle="modal" data-bs-target="#social-media-share"><i class="fa-regular fa-share-from-square"></i></a>
      {% if is_bookmarked %}
      <a href="{% url 'remove_bookmark' recipe.slug %}" class="bookmark-icon me-3"><i class="fas fa-bookmark"></i></a>
      {% else %}
      <a href="{% url 'bookmark_recipe' recipe.slug %}" class="bookmark-icon me-3"><i class="far fa-bookmark"></i></a>
      {% endif %}
    </div>
  </div>

  <!-- Info Section -->
  <div class="d-flex flex-wrap recipe-info">
      <div class="my-2 mx-4">
        {% if recipe.user.profile.image %}
          <a href="{% url 'profile' recipe.user.profile.id %}" aria-label="Click to view user profile {{recipe.user.username}}">
            <img src="{{ recipe.user.profile.image.url }}" class="rounded-circle avatar" alt="{{ recipe.user.username }} Profile Photo">
          </a>
        {% else %}
            <img src="{% static 'images/zaitouna_icon.svg' %}" class="rounded-circle avatar" alt="Default Profile Photo">
        {% endif %}
        <small class="pl-1">{{recipe.user}}</small>
      </div>
      <div class="my-2 mx-4 tools">
        <i class="far fa-calendar-alt"></i>
        <small>{{recipe.posted_date}}</small>
      </div>
      <div class="my-2 mx-4 tools">
        <i class="fa-regular fa-comment"></i>
        <small>{{ comment_count }}</small>
      </div>
      <div class="my-2 mx-4 tools">
          <form id="rating-form" method="POST" action="{% url 'rate_recipe' recipe.id %}">
              {% csrf_token %}

              <input type="hidden" id="rating-value" name="rating" value="0">
                {% for i in star_range %}
                    {% if i <= average_rating %}
                        <i class="star fas fa-star" data-rating="{{i}}"></i>  <!-- Filled star -->
                    {% else %}
                        <i class="star far fa-star" data-rating="{{i}}"></i>
                    {% endif %}
                {% endfor %}
              <span data-average="{% if average_rating is None %}0{% else %}{{ average_rating }}{% endif %}">
                <small>{{rating_count}} </small></span>
          </form>
      </div>

  </div>

  <!-- Description Section -->
  <div class="row mt-3 recipe-desc">
    <div class="col">
      <p>{{recipe.description}}</p>
    </div>
  </div>

  <!-- Recipe Photo -->
  <div class="row mt-3">
    <div class="col">
      <img src="{{recipe.image.url}}" class="img-fluid recipe-img" alt="{{recipe.image_alt}}">
    </div>
  </div>

  <!-- Recipe Instructions and Details -->
  <div class="row mt-3">
    <!-- Instructions -->
    <div class="col-md-9">
      <h2>Ingredients</h2>
      {{recipe.ingredients | safe }}
      <!-- More Steps -->
    </div>
    <!-- Recipe Details -->
    <div class="col-md-3">
      <h2>Details</h2>
      <ul class="list-unstyled ">
        <li class="tools">
          <small><i class="fa-solid fa-wine-glass-empty"></i> Meal Type</small>
          <span><strong>{{recipe.meal_type}} </strong></span>
        </li>
        <li class="tools">
          <small><i class="far fa-clock"></i> Cook Time</small>
          <span><strong>{{recipe.prep_time}} min</strong></span>
        </li>
        <li class="tools">
          <small><i class="fa-solid fa-scale-unbalanced-flip"></i> Difficulty</small>
          <span><strong>{{recipe.get_difficulty_display}}</strong> </span>
        </li>
        <li class="tools">
          <small><i class="fa-solid fa-bell-concierge"></i> Serves</small>
          <span><strong>{{recipe.serves}} People</strong></span>
        </li>
      </ul>
    </div>
  </div>


  <div class="row m-2">
    <h2>Instructions</h2>
      {{recipe.instructions | safe }}
  </div>
</div>

<section class="container">
    <!--Comments -->
    <div class=" comments">
    {% if comments %}
        {% for comment in comments %}
        <div class="row">
        <!-- Media object -->
            <div class=" d-flex comment {% if not comment.approved and comment.author == user %}faded{% elif not comment.approved %} d-none{% endif %}">
              <!-- Image -->
              <a href="{% url 'profile' comment.author.profile.id %}" aria-label="Click to view user profile {{comment.author.username}}">
                    {% if comment.author.profile.image %}
                        <img src="{{ comment.author.profile.image.url }}" class="me-3 rounded-circle" style="width: 60px; height: 60px;" alt="{{ comment.author.username }} Profile Photo">
                    {% else %}
                        <img src="{% static 'images/zaitouna_icon.svg' %}" class="me-3 rounded-circle" style="width: 60px; height: 60px;" alt="Default Profile Photo">
                    {% endif %}
              </a>
              <!-- Media body -->
              <div class="media-body">
                  <h5 class="fw-bold">{{comment.author}}</h5>
                  <small class="text-muted">Posted on  {{ comment.created_on }}</small>
                  <p id="comment-title{{ comment.id }}">{{ comment.title }}</p>
                  <p id="comment-body{{ comment.id }}">{{ comment.body  }}</p>
                  {% if not comment.approved and comment.author == user %}
                    <p class="approval">This comment is awaiting approval</p>
                  {% endif %}
              </div>
              <!--End Media body -->
              <div class="ms-auto">
                {% if user.is_authenticated and comment.author == user %}
                    <button class="btn btn-edit d-flex comment-icon" comment_id="{{ comment.id }}"><i class="fa-regular fa-pen-to-square"></i></button>
                    <button class="btn btn-delete  d-flex comment-icon" comment_id="{{ comment.id }}"><i class="fa-regular fa-trash-can"></i></button>
                {% endif %}
              </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% else %}
      <div class="form-title my-4">
                <h1>Did you Try this Recipe?</h1>
      </div>
      <h5>Share your Experience with us</h5>
    {% endif %}



<!--  Comments -->
  <!-- Displaying Comments -->
  <div class="row my-4 mx-2 comments-add">
    <!-- Creating New Comments -->
      <div class="card-body">
        {% if user.is_authenticated %}
        <div class="form-title my-4">
            <h1>Leave a Comment</h1>
        </div>
        <p>Posting as: {{ user.username }}</p>
        <form id="commentForm" method="post">
          {{ comment_form | crispy }}
          {% csrf_token %}
          <button id="submitButton" type="submit"
            class="btn btn-primary ">Send</button>
        </form>
        {% else %}
        <p>Log in to leave a comment</p>
        {% endif %}
      </div>
  </div>
</section>


<!-- Modals -->
<!-- Social Media share Modal -->
<div class="modal fade" id="social-media-share" tabindex="-1" aria-labelledby="socialMediaModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Share it Now</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
     <p class="text-center p-3"> Tell you friends about the Recipe</p>
      <div class="social-modal-body d-flex justify-content-center">
        {% post_to_facebook object_or_url "<i class='fa-brands fa-facebook m-3'></i>" %}
        {% post_to_twitter "New Song: {{object.title}}. Check it out!" object_or_url "<i class='fa-brands fa-square-twitter m-3'></i>" %}
        {% send_email object.title "Look at this recipe: {{object.name}}. Check it out!" object_or_url "<i class='fa-solid fa-envelope m-3'></i>" %}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
<!-- Delete confirmation modal -->
<div class="modal fade" id="deleteModal" tabindex="-1"
  aria-labelledby="deleteModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title"
          id="deleteModalLabel">Delete comment?</h5>
        <button type="button" class="btn-close"
          data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        Are you sure you want to delete your comment?
        This action cannot be undone.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary"
          data-bs-dismiss="modal">Close</button>
        <a id="deleteConfirm" href="#" class="btn
          btn-danger">Delete</a>
      </div>
    </div>
  </div>
</div>

{% endblock %}

recipes/templates/recipes/recipe_home_list.html
{% load static %}
    <div class="form-title text-center p-4 justify-content-center">
            <h1>Latest Recipes</h1>
    </div>
    <div class="row row-cols-1 row-cols-md-3 g-4">
<!--        <div class="card-group">-->
        {% for recipe in recipe_list %}
<!--        <a href="" class="recipes" aria-label="Click to view {{recipe.title}}"></a>-->

        <div class="card-group">
<!--            <div class="col">-->
                <div class="card recipe-card">
                      <a href="{% url 'recipe_detail' recipe.slug %}"  aria-label="Click to view {{recipe.title}}">
                          <img src="{{recipe.image.url}}" class="card-img-top" alt="{{recipe.image_alt}}">
                      </a>
                    <div class="card-body">
                        <h2 class="card-title">{{recipe.name}}</h2>
                        <p class="card-author">
                            {% if recipe.user.profile.image %}
                                <a href="{% url 'profile' recipe.user.profile.id %}" aria-label="Click to view user profile {{recipe.user.username}}">
                                <img src="{{ recipe.user.profile.image.url }}" class="rounded-circle avatar" alt="{{ recipe.user.username }} Profile Photo">
                                </a>
                            {% else %}
                                <img src="{% static 'images/zaitouna_icon.svg' %}" class="rounded-circle avatar" alt="Default Profile Photo">
                            {% endif %}
                            {{ recipe.user.username }} | <i class="far fa-calendar-alt"></i> {{recipe.posted_date}}
                        </p>
                        <span class="badge rounded-pill bg-success">{{recipe.meal_type}}</span>
                        <span class="badge rounded-pill bg-success">{{recipe.get_difficulty_display}}</span>
                        <span class="badge rounded-pill bg-success">cook time : {{recipe.prep_time}} min</span>
                        <span class="badge rounded-pill bg-success">serves :{{recipe.serves}}</span>
                        <p class="card-text py-3">{{recipe.description}}</p>
                    </div>
                    <div class="card-footer bg-transparent border-success">
                        <a href="{% url 'recipe_detail' recipe.slug %}"  aria-label="Click to view {{recipe.title}}" class="btn btn-primary ">Learn More</a>
                        <span>
                        {% for i in star_range %}
                            {% if i <= recipe.average_rating %}
                                <i class="star fas fa-star"></i>  <!-- Filled star -->
                            {% else %}
                                <i class="star far fa-star"></i>  <!-- Empty star -->
                            {% endif %}
                        {% endfor %}
                        </span>
                    </div>
<!--                </div>-->
            </div>
        </div>
        {% endfor %}
<!--        </div>-->

    </div>
    <!-- Pagination controls -->

    <div class="my-4">
        <nav aria-label="Page navigation example">
          <ul class="pagination justify-content-center">
            {% if recipe_list.has_previous %}
              <li class="page-item">
                <a class="page-link" href="?page=1" tabindex="-1" aria-disabled="true">&laquo; First</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ recipe_list.previous_page_number }}">Previous</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">&laquo; First</span>
              </li>
              <li class="page-item disabled">
                <span class="page-link">Previous</span>
              </li>
            {% endif %}

            {% for num in recipe_list.paginator.page_range %}
              {% if num == recipe_list.number %}
                <li class="page-item active" aria-current="page">
                  <span class="page-link">{{ num }}</span>
                </li>
              {% else %}
                <li class="page-item">
                  <a class="page-link" href="?page={{ num }}">{{ num }}</a>
                </li>
              {% endif %}
            {% endfor %}

            {% if recipe_list.has_next %}
              <li class="page-item">
                <a class="page-link" href="?page={{ recipe_list.next_page_number }}">Next</a>
              </li>
              <li class="page-item">
                <a class="page-link" href="?page={{ recipe_list.paginator.num_pages }}">Last &raquo;</a>
              </li>
            {% else %}
              <li class="page-item disabled">
                <span class="page-link">Next</span>
              </li>
              <li class="page-item disabled">
                <span class="page-link">Last &raquo;</span>
              </li>
            {% endif %}
          </ul>
        </nav>
    </div>